# Generated by Django 5.2.3 on 2025-06-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='emai',
        ),
    ]
