# Generated by Django 5.2.3 on 2025-06-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuariopersonalizado_emai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='documento',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_documento',
            field=models.CharField(max_length=15),
        ),
    ]
