# Generated by Django 5.2.3 on 2025-06-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuariopersonalizado_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
