# Generated by Django 5.2.3 on 2025-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuariopersonalizado_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('secretaria', 'Secretaria'), ('invitado', 'Invitado'), ('visitante', 'Visitante')], max_length=15),
        ),
    ]
