# Generated by Django 5.2.3 on 2025-07-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuariopersonalizado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Secretaria', 'Secretaria'), ('Invitado', 'Invitado'), ('Visitante', 'Visitante')], max_length=15),
        ),
    ]
