# Generated by Django 5.2.3 on 2025-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuariopersonalizado_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=10),
        ),
    ]
