# Generated by Django 5.2.3 on 2025-06-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_art', models.CharField(max_length=100)),
                ('no_referencia', models.CharField(max_length=50, unique=True)),
                ('presentacion', models.CharField(choices=[('unidad', 'Unidad'), ('barril', 'Barril'), ('balde', 'Balde'), ('galon', 'Galón'), ('cuarto', 'Cuarto')], max_length=10)),
                ('stock', models.PositiveIntegerField()),
                ('stock_min', models.PositiveIntegerField()),
                ('stock_max', models.PositiveIntegerField()),
            ],
        ),
    ]
