# Generated by Django 5.2.3 on 2025-06-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='nombre_art',
            new_name='nombre_articulo',
        ),
    ]
