# Generated by Django 5.2.3 on 2025-06-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_rename_nombre_art_articulo_nombre_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='nombre_articulo',
            new_name='nombre_art',
        ),
    ]
