# Generated by Django 5.2.3 on 2025-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_salidafactura_detallesalida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidafactura',
            old_name='fecha',
            new_name='fecha_salida',
        ),
        migrations.AlterField(
            model_name='entradafactura',
            name='fecha_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
