# Generated by Django 4.1.3 on 2025-07-22 00:14

import ajustes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=ajustes.models.ruta_imagen_inicio)),
            ],
        ),
    ]
