# Generated by Django 5.2.3 on 2025-06-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rol',
        ),
    ]
