# Generated by Django 5.2.3 on 2025-06-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='placa',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
